language: php
cache:
  directories:
    - $HOME/.composer/cache
install: travis_retry composer install --no-interaction --prefer-dist --no-suggest;
script: vendor/bin/phpunit
php:
  - '5.6'
  - '7.0'
  - '7.1'